name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: cd gradle-gitignore-plugin && chmod +x gradlew
      - name: Publish to Github Artifact Repository
        env:
          GPP_KEY: ${{ secrets.GPP_KEY }}
          GPP_SECRET: ${{ secrets.GPP_SECRET }}
        run: cd gradle-gitignore-plugin && ./gradlew build funcTest publishPlugins -Pgradle.publish.key=$GPP_KEY -Pgradle.publish.secret=$GPP_SECRET